"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import type { GuideProduct, GuideReply } from "../../lib/rehmat-guide";
import {COMMERCE_ENABLED} from "../../lib/commerce";
import {useCart} from "./cart-provider";

type CalendarProduct={slug:string;name:string;reason:string;image:string;imageAlt:string;pricePaise:number|null;sizes:number[];availability:string;notes:{top:string[];heart:string[];base:string[]}|null};
type Calendar={dateKey:string;weekday:string;festival:{name:string;date:string;headline:string;description:string}|null;nextFestival:{name:string;date:string}|null;recommendation:CalendarProduct|null;coupon:{code:string;description:string;expiresAt:string|null;minimumSubtotalPaise:number;firstOrderOnly:boolean;freeShipping:boolean}|null};
type Config={enabled:boolean;greeting:string;prompts:string[];calendar:Calendar;whatsapp:{enabled:boolean;number:string;notice:string};source:string};
type Message={id:number;role:"guide"|"visitor";text:string;products?:GuideProduct[];layering?:boolean;sources?:Array<{title:string;url:string;license:string}>};
const money=(paise:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(paise/100);
const indianDate=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"long",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${value}T12:00:00+05:30`));

export function RehmatGuide(){
  const cart=useCart();
  const [open,setOpen]=useState(false),[mode,setMode]=useState<"calendar"|"assistant">("calendar"),[config,setConfig]=useState<Config|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const panel=useRef<HTMLDivElement>(null),launcher=useRef<HTMLButtonElement>(null),field=useRef<HTMLInputElement>(null),contextProductId=useRef<string|undefined>(undefined),sessionId=useRef(""),lastProducts=useRef<string[]>([]),messageId=useRef(2);
  useEffect(()=>{sessionId.current=crypto.randomUUID().replaceAll("-","");},[]);
  useEffect(()=>{fetch("/api/rehmat-guide").then(r=>r.json()).then((value:Config)=>{setConfig(value);setMessages([{id:1,role:"guide",text:value.greeting}]);}).catch(()=>setError("Rehmat AI could not be loaded."));},[]);
  useEffect(()=>{const show=(event:Event)=>{const detail=(event as CustomEvent<{productId?:string;productName?:string}>).detail;contextProductId.current=detail?.productId;if(detail?.productName){setInput(`Tell me about ${detail.productName}`);setMode("assistant");}setOpen(true);};window.addEventListener("open-rehmat-guide",show);return()=>window.removeEventListener("open-rehmat-guide",show);},[]);
  useEffect(()=>{const show=()=>{if(window.location.hash==="#rehmat-guide")setOpen(true);};show();window.addEventListener("hashchange",show);return()=>window.removeEventListener("hashchange",show);},[]);
  useEffect(()=>{if(!open)return;if(mode==="assistant")field.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);launcher.current?.focus();return;}if(event.key!=="Tab"||!panel.current)return;const controls=[...panel.current.querySelectorAll<HTMLElement>('a,button,input:not([disabled])')];if(!controls.length)return;const first=controls[0],last=controls.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[open,mode]);
  async function ask(text:string){const clean=text.trim();if(!clean||loading)return;const context=messages.slice(-6).map(message=>`${message.role}: ${message.text}`);setMessages(v=>[...v,{id:messageId.current++,role:"visitor",text:clean}]);setInput("");setLoading(true);setError("");const rejection=/don'?t like|not that|less sweet|different/i.test(clean);try{const response=await fetch("/api/rehmat-guide",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:clean,productId:contextProductId.current,sessionId:sessionId.current,excludedProductSlugs:rejection?lastProducts.current:[],context})});const value=await response.json() as GuideReply&{message:string};if(!response.ok)throw new Error(value.message);lastProducts.current=value.products.map(product=>product.slug);setMessages(v=>[...v,{id:messageId.current++,role:"guide",text:value.message,products:value.products,layering:value.layering,sources:value.sources}]);}catch(cause){setError(cause instanceof Error?cause.message:"Please try again.");}finally{setLoading(false);}}
  function submit(event:FormEvent){event.preventDefault();void ask(input);}
  function whatsapp(products:GuideProduct[],layering=false){const lines=products.map(p=>`${p.name}: ${p.variants.map(v=>`${v.sizeMl} ml ${money(v.pricePaise)}`).join(" / ")}`);const number=String(config?.whatsapp.number??"").replace(/\D/g,"").slice(0,15);return `https://wa.me/${number}?text=${encodeURIComponent(`Sat Sri Akal, I would like to ask about ${layering?"this layering combination":"these fragrances"}:\n${lines.join("\n")}\nPlease confirm availability and ordering details.`)}`;}
  function add(product:GuideProduct){const variant=product.variants[0];if(!variant)return;cart.add({variantId:variant.id,productSlug:product.slug,productName:product.name,sizeMl:variant.sizeMl,sku:variant.sku,unitPricePaise:variant.pricePaise,currency:"INR",image:product.image,maxQuantity:variant.availableQuantity,quantity:1});}
  if(config&&!config.enabled)return null;
  const calendar=config?.calendar,recommendation=calendar?.recommendation;
  return <>
    <button id="rehmat-guide" ref={launcher} className="guide-launcher" type="button" aria-label="Rehmat AI is available" aria-expanded={open} aria-controls="rehmat-guide-panel" onClick={()=>setOpen(true)}><span aria-hidden="true">R</span><b>Ask Rehmat AI</b><i aria-hidden="true"/></button>
    {open&&<div className="guide-shell" role="presentation"><button className="guide-scrim" aria-label="Close Rehmat AI" onClick={()=>setOpen(false)}/><div ref={panel} id="rehmat-guide-panel" className="guide-panel" role="dialog" aria-modal="true" aria-labelledby="guide-title">
      <header><div><p>Rehmat Panjab</p><h2 id="guide-title">Rehmat AI</h2><span>Calendar and fragrance intelligence</span></div><button type="button" aria-label="Close Rehmat AI" onClick={()=>{setOpen(false);launcher.current?.focus();}}>×</button></header>
      <div className="guide-mode-tabs" role="tablist" aria-label="Rehmat AI features"><button id="guide-calendar-tab" role="tab" aria-selected={mode==="calendar"} aria-controls="guide-calendar" onClick={()=>setMode("calendar")}>Calendar</button><button id="guide-assistant-tab" role="tab" aria-selected={mode==="assistant"} aria-controls="guide-assistant" onClick={()=>setMode("assistant")}>AI Assistant</button></div>
      {mode==="calendar"?<section id="guide-calendar" className="guide-calendar" role="tabpanel" aria-labelledby="guide-calendar-tab">
        <div className="guide-calendar-date"><p>{calendar?.weekday??"India time"}</p><strong>{calendar?indianDate(calendar.dateKey):"Loading…"}</strong></div>
        {calendar?.festival?<div className="guide-festival"><p className="eyebrow">Festival edit · until {indianDate(calendar.festival.date)}</p><h3>{calendar.festival.headline}</h3><p>{calendar.festival.description}</p></div>:calendar?.nextFestival?<p className="guide-next-festival">Next verified festival edit: <strong>{calendar.nextFestival.name}</strong> · {indianDate(calendar.nextFestival.date)}. It will appear ten days before the verified date.</p>:null}
        {recommendation?<article className="guide-calendar-product"><Image src={recommendation.image} alt={recommendation.imageAlt} width={140} height={176}/><div><p className="eyebrow">Today’s Rehmat</p><h3>{recommendation.name}</h3><p>{recommendation.reason}</p><p className="guide-notes">{recommendation.notes?[...recommendation.notes.base,...recommendation.notes.heart,...recommendation.notes.top].slice(0,6).join(" · "):"Verified profile available on the product page"}</p><strong>{recommendation.pricePaise===null?"Price on request":`From ${money(recommendation.pricePaise)}`}</strong><small>{recommendation.sizes.join(" / ")} ml · {recommendation.availability}</small><Link href={`/product/${recommendation.slug}`}>View today’s fragrance</Link></div></article>:null}
        {calendar?.coupon?<aside className="guide-coupon"><p className="eyebrow">Live offer</p><strong>{calendar.coupon.code}</strong><p>{calendar.coupon.description}{calendar.coupon.minimumSubtotalPaise?` · Minimum ${money(calendar.coupon.minimumSubtotalPaise)}`:""}{calendar.coupon.firstOrderOnly?" · First order only":""}</p><small>Eligibility and availability are validated at checkout.</small></aside>:<p className="guide-no-offer">No public coupon is active right now. Rehmat AI will only show verified live offers.</p>}
      </section>:<section id="guide-assistant" className="guide-assistant" role="tabpanel" aria-labelledby="guide-assistant-tab">
        <div className="guide-messages" aria-live="polite">{messages.map(message=><article key={message.id} className={`guide-message is-${message.role}`}><p>{message.text}</p>{message.sources?.length?<p className="guide-sources">Sources: {message.sources.map((source,index)=><span key={source.url}>{index?" · ":""}<a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> ({source.license})</span>)}</p>:null}{message.products?.map(product=><section className="guide-product" key={product.slug}><Image src={product.image} alt={product.imageAlt} width={96} height={120}/><div><h3>{product.name}</h3>{product.inspirationLine&&<small>{product.inspirationLine}</small>}<p>{product.reason}</p><p className="guide-notes">{product.notes?[...product.notes.top,...product.notes.heart,...product.notes.base].slice(0,5).join(" · "):product.atmosphere}</p><p>{product.variants.length?product.variants.map(v=>`${v.sizeMl} ml · ${money(v.pricePaise)} · ${v.availableQuantity} available`).join(" | "):"No orderable size available"}</p><div><Link href={`/product/${product.slug}`}>View product</Link>{COMMERCE_ENABLED&&product.variants.length?<button type="button" onClick={()=>add(product)}>Add to cart</button>:null}</div></div></section>)}{message.products?.length&&config?.whatsapp.enabled?<a className="guide-whatsapp" href={whatsapp(message.products,message.layering)} target="_blank" rel="noreferrer">Add to WhatsApp order</a>:null}</article>)}{loading&&<p className="guide-status">Considering the live collection…</p>}{error&&<p className="guide-error" role="alert">{error}</p>}</div>
        {messages.length===1&&<div className="guide-prompts">{config?.prompts.slice(0,6).map(prompt=><button type="button" key={prompt} onClick={()=>void ask(prompt)}>{prompt}</button>)}</div>}
        <form onSubmit={submit}><label htmlFor="guide-input" className="sr-only">Ask Rehmat AI about fragrance</label><input ref={field} id="guide-input" value={input} maxLength={360} onChange={e=>setInput(e.target.value)} placeholder="Describe a scent, occasion, budget or layering idea…" disabled={loading}/><button type="submit" disabled={loading||!input.trim()} aria-label="Send fragrance question">Send</button></form>
      </section>}
      <footer><button type="button" onClick={()=>{setMessages(config?[{id:messageId.current++,role:"guide",text:config.greeting}]:[]);lastProducts.current=[];contextProductId.current=undefined;sessionId.current=crypto.randomUUID().replaceAll("-","");setError("");}}>Reset conversation</button><span>{config?.source==="deterministic"?"Grounded catalogue intelligence":"Grounded AI with safe fallback"}</span></footer>
    </div></div>}
  </>;
}
