import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {addressPreview,deliveryAddressSchema,normalizeIndianMobile} from "../lib/address";
import {calculateShipping} from "../lib/shipping";

const rural={recipientName:"ਹਰਕੀਰਤ ਸਿੰਘ",mobile:"98765 43210",alternateMobile:"",email:"customer@example.com",house:"House 14",streetVillage:"Village Bagli Khurd",locality:"Near Gurudwara Sahib",landmark:"",city:"Samrala",district:"Ludhiana",state:"Punjab",pinCode:"141412",country:"India" as const,addressType:"Home" as const,instructions:"Call on arrival"};
test("complete rural Indian address normalizes and previews without truncation",()=>{const parsed=deliveryAddressSchema.parse(rural);assert.equal(parsed.mobile,"+919876543210");assert.match(addressPreview(parsed),/Village Bagli Khurd/);assert.match(addressPreview(parsed),/141412, India/);assert.equal(normalizeIndianMobile("+91-98765-43210"),"+919876543210");assert.equal(normalizeIndianMobile("12345"),null);assert.throws(()=>deliveryAddressSchema.parse({...rural,pinCode:"14141"}));});
test("shipping preserves exact PIN and ₹1,500 threshold safeguards",()=>{assert.equal(calculateShipping(149999,"141412",{autoLocalDeliveryEnabled:false,approvedPins:["141412"]}).deliveryMethod,"standard_shipping_pending");assert.equal(calculateShipping(150000,"999999",{autoLocalDeliveryEnabled:false,approvedPins:["141412"]}).deliveryMethod,"free_standard_shipping");assert.equal(calculateShipping(10000,"141412",{autoLocalDeliveryEnabled:true,approvedPins:["141412"]}).deliveryMethod,"free_local_delivery");});
test("saved addresses are owner-scoped and WhatsApp omits email",()=>{const migration=readFileSync("supabase/migrations/202609100002_customer_addresses_hybrid_guide.sql","utf8"),api=readFileSync("app/api/addresses/route.ts","utf8"),whatsapp=readFileSync("app/components/whatsapp-order.tsx","utf8"),checkout=readFileSync("app/api/create-order/route.ts","utf8");assert.match(migration,/user_id=auth\.uid\(\)/);assert.match(migration,/unique index.*one_default/i);assert.match(api,/\.eq\("user_id",auth\.user\.id\)/);assert.match(whatsapp,/Email is used for order service only and is not included/);assert.doesNotMatch(whatsapp,/`Email:/);assert.match(checkout,/billing_snapshot/);assert.match(checkout,/delivery_snapshot/);});
test("server-only adapters expose no public secret variables",()=>{const ai=readFileSync("lib/fragrance-ai.ts","utf8"),shiprocket=readFileSync("lib/shiprocket.ts","utf8");assert.doesNotMatch(ai,/NEXT_PUBLIC_/);assert.match(ai,/redactPersonalData/);assert.match(ai,/AbortSignal\.timeout/);assert.doesNotMatch(shiprocket,/NEXT_PUBLIC_/);assert.match(shiprocket,/inactive until KYC/);});
