import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("approved merchant and India shipping facts are version controlled",async()=>{const [templates,migration,correction,merchant]=await Promise.all([read("lib/policy-templates.ts"),read("supabase/migrations/202609100001_launch_contact_shipping_gulnaar.sql"),read("supabase/migrations/202609100003_contact_and_razorpay_profile.sql"),read("lib/merchant.ts")]);for(const value of ["Rehmat Panjab","+91 70094 64475","support@rehmatpanjab.com","India only","1–2 business days","3–7 business days","₹1,500"])assert.match(`${templates}\n${migration}\n${correction}\n${merchant}`,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(templates,/Cash on Delivery is not available/);assert.doesNotMatch(templates,/COD available|Cash on Delivery is available/i);});

test("returns and refund copy preserves the approved customer process",async()=>{const templates=await read("lib/policy-templates.ts");for(const value of ["within 12 hours","No change-of-mind returns","opened or used","within four hours","continuous unboxing video","within two business days","outside Rehmat Panjab’s direct control","Original shipping charges are non-refundable","coupon NEW"])assert.match(templates,new RegExp(value,"i"));});

test("terms disclose WhatsApp, payment safeguards, coupon and inspiration status",async()=>{const [templates,commerce]=await Promise.all([read("lib/policy-templates.ts"),read("lib/commerce.ts")]);assert.match(templates,/WhatsApp message is an order request/);assert.match(templates,/Online checkout is not currently active/);assert.match(templates,/eligible first-time customer 15% off/);assert.match(templates,/not affiliated with, endorsed by or licensed by/);assert.match(commerce,/NEXT_PUBLIC_COMMERCE_ENABLED\s*===\s*"true"/);});

test("publication is blocked until operational verification and versions are retained",async()=>{const [migration,api,page]=await Promise.all([read("supabase/migrations/202609100001_launch_contact_shipping_gulnaar.sql"),read("app/api/admin/policies/route.ts"),read("app/policies/[slug]/page.tsx")]);for(const field of ["support_email_verified_at","support_phone_confirmed_at","shipping_calculation_verified_at"])assert.match(migration,new RegExp(field));assert.match(migration,/publish_status='draft'/);assert.match(migration,/store_policy_versions/);assert.match(api,/Publishing is blocked until mailbox, phone and shipping checks are verified/);assert.match(page,/getPublishedPolicyRecord/);});
test("published policy versions cannot be overwritten",async()=>{const [migration,api]=await Promise.all([read("supabase/migrations/202609090004_customer_policy_drafts.sql"),read("app/api/admin/policies/route.ts")]);assert.match(migration,/on conflict\(version\) do nothing/);assert.match(api,/published policy version is immutable/i);});

test("checkout records policy acceptance without preselecting marketing",async()=>{const [migration,checkout,order]=await Promise.all([read("supabase/migrations/202609090004_customer_policy_drafts.sql"),read("app/components/razorpay-checkout.tsx"),read("app/api/create-order/route.ts")]);assert.match(migration,/marketing_consent boolean not null default false/);assert.match(checkout,/useState\(false\).*marketingConsent|marketingConsent.*useState\(false\)/s);assert.match(checkout,/termsAccepted/);assert.match(checkout,/returnsAccepted/);assert.match(order,/policy_version:publishedPolicy\.version/);assert.match(order,/policies_accepted_at:new Date\(\)\.toISOString\(\)/);});

test("cookie choices and print-friendly policy layout are present",async()=>{const [cookies,css]=await Promise.all([read("app/components/cookie-preferences.tsx"),read("app/globals.css")]);assert.match(cookies,/Reject non-essential/);assert.match(cookies,/Accept optional cookies/);assert.match(cookies,/localStorage/);assert.match(css,/@media print/);assert.match(css,/policy-document/);});
