import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Our Story replaces the fixed five-product discovery route",async()=>{const [story,swipe]=await Promise.all([read("app/discover/page.tsx"),read("app/discover/swipe-discovery.tsx")]);for(const copy of [/Perfume oil,[\s\S]*worn close\./i,/A name carried with grace\./i,/Your oil\. Your atmosphere\./i,/Made to be worn\.[\s\S]*Not announced\./i])assert.match(story,copy);assert.doesNotMatch(story,/SwipeDiscovery|Meet the five|five-product/i);assert.doesNotMatch(swipe,/\/ 05|Meet the five/i);});

test("bottles are UUID-linked, archive-only and snapshot into future order items",async()=>{const [migration,api,storefront,purchase,checkout]=await Promise.all([read("supabase/migrations/202609090002_bottles_policy_readiness.sql"),read("app/api/admin/bottles/route.ts"),read("lib/storefront.ts"),read("app/components/product-purchase.tsx"),read("app/api/create-order/route.ts")]);assert.match(migration,/bottle_id uuid references public\.bottles\(id\) on delete restrict/);assert.match(migration,/bottle_snapshot jsonb/);assert.match(migration,/before insert on public\.order_items/);assert.match(migration,/must be archived, not deleted/);assert.doesNotMatch(migration,/update public\.inventory/i);assert.match(api,/role!=="super_admin"/);assert.match(api,/status:"archived"/);assert.match(storefront,/bottleValue\?\.status==="active"/);assert.match(storefront,/variant\.enabled && variant\.bottle/);assert.match(checkout,/activeBottleIds/);assert.match(purchase,/Available formats/);});

test("homepage is compact and Rehmat Guide remains primary",async()=>{const [home,button]=await Promise.all([read("app/page.tsx"),read("app/components/open-guide-button.tsx")]);assert.match(home,/Not sure where/);assert.match(button,/Ask Rehmat Guide/);assert.match(home,/house-preview/);assert.doesNotMatch(home,/Find mine|Create mine|Shape the next/);});

test("cursor has native fallbacks, cleanup and one restrained ripple",async()=>{const [cursor,styles]=await Promise.all([read("app/components/rehmat-oil-cursor.tsx"),read("app/globals.css")]);for(const value of [/requestAnimationFrame/,/removeEventListener/,/timers\.forEach/,/pointer-events: none/,/prefers-reduced-motion/,/pointer: fine/])assert.match(cursor+styles,value);assert.match(cursor,/startsWith\("\/admin"\)/);assert.doesNotMatch(cursor,/split|speck|spill/i);});

test("policy readiness is structured and blocks checkout without complete owner facts",async()=>{const [settings,policy,templates,createOrder,migration]=await Promise.all([read("lib/store-settings-schema.ts"),read("app/policies/[slug]/page.tsx"),read("lib/policy-templates.ts"),read("app/api/create-order/route.ts"),read("supabase/migrations/202609090002_bottles_policy_readiness.sql")]);for(const value of ["privacyContactEmail","openedOilRule","governingLawJurisdiction","deliveryAttemptRules"])assert.match(settings,new RegExp(value));assert.doesNotMatch(`${policy}\n${templates}`,/owner must|provide an email|Owner input required/i);assert.match(templates,/WhatsApp message is an order request/);assert.match(createOrder,/policiesComplete/);assert.match(migration,/publish_status='published'/);assert.doesNotMatch(migration,/set quantity/i);});

test("Razorpay stays inactive and inventory source remains unchanged",async()=>{const [commerce,home,guide]=await Promise.all([read("lib/commerce.ts"),read("app/page.tsx"),read("app/components/rehmat-guide.tsx")]);assert.match(commerce,/=== "true"/);assert.doesNotMatch(home,/Razorpay|Secure payments/);assert.match(guide,/open-rehmat-guide/);});
