import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";
import {buyTwoGiftSaving,chooseBestPromotion,festivalSaving} from "../lib/promotions.mjs";
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("festival tiers use IST boundaries and cap the saving",()=>{assert.equal(festivalSaving(99900,new Date("2026-10-08T18:29:59Z")),null);assert.equal(festivalSaving(99900,new Date("2026-10-08T18:30:00Z")).savingPaise,9990);assert.equal(festivalSaving(149900,new Date("2026-10-10T00:00:00Z")).percent,20);assert.equal(festivalSaving(400000,new Date("2026-10-23T18:29:59Z")).savingPaise,90000);assert.equal(festivalSaving(99900,new Date("2026-10-23T18:30:00Z")),null);});
test("buy two 6 ml reward is limited to one stock-backed gift",()=>{assert.equal(buyTwoGiftSaving({paidSixMlQuantity:1,rewardPricePaise:19900,rewardAvailableQuantity:5,rewardVariantId:"v"}),null);assert.equal(buyTwoGiftSaving({paidSixMlQuantity:4,rewardPricePaise:19900,rewardAvailableQuantity:0,rewardVariantId:"v"}),null);const reward=buyTwoGiftSaving({paidSixMlQuantity:4,rewardPricePaise:19900,rewardAvailableQuantity:2,rewardVariantId:"v"});assert.equal(reward.rewardQuantity,1);assert.equal(reward.savingPaise,19900);});
test("only the single highest promotion wins",()=>{assert.equal(chooseBestPromotion([{kind:"coupon",savingPaise:20000,priority:50},{kind:"festival",savingPaise:30000,priority:30},{kind:"gift",savingPaise:15000,priority:20}]).kind,"festival");});
test("reward ledger is immutable and checkout inventory remains idempotent",()=>{const sql=read("supabase/migrations/202610010001_promotions_rewards_readiness.sql");assert.match(sql,/Reward stamp ledger entries are immutable/);assert.match(sql,/on conflict\(idempotency_key\) do nothing/);assert.match(sql,/if target_order\.status='paid'/);assert.match(sql,/quantity-reserved>=item\.quantity/);assert.match(sql,/missing an approved 6 ml or 12 ml variant/);assert.match(sql,/A 3 ml tester is optional until its separate content, packaging and margin/);});
test("webhook uses raw signed body and partial refunds require review",()=>{const source=read("app/api/razorpay/webhook/route.ts");assert.match(source,/const body=await request\.text\(\)/);assert.match(source,/verifyRazorpayWebhookSignature\(body,signature,secret\)/);assert.match(source,/duplicate:true/);assert.match(source,/reward_adjustment_reviews/);});
test("Razorpay remains gated and server quote owns price and reward",()=>{const order=read("app/api/create-order/route.ts"),checkout=read("lib/commerce.ts");assert.match(order,/variant\.price_paise/);assert.match(order,/register_checkout_attempt/);assert.match(order,/calculateOrderQuote/);assert.match(checkout,/NEXT_PUBLIC_COMMERCE_ENABLED/);});
