import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { StorefrontProduct } from "../lib/catalog";
import { PRODUCT_MEDIA_MANIFEST, mediaForSlug } from "../lib/product-media-manifest";
import { createGuideReply, sanitizeGuideInput } from "../lib/rehmat-guide";

const slugs=["musk-rizali","vanilla-musk","white-oud","oud-rose","junoon","red-musk","nazakat","zara-candy","deer-musk","afsoon"] as const;
test("all ten stable slugs own exact campaign roles and alt text",()=>{assert.deepEqual(Object.keys(PRODUCT_MEDIA_MANIFEST),slugs);for(const slug of slugs){const media=mediaForSlug(slug)!;assert.match(media.card,new RegExp(`/${slug}-card\\.webp$`));assert.match(media.hero,new RegExp(`/${slug}-hero\\.webp$`));assert.match(media.social,new RegExp(`/${slug}-social\\.webp$`));assert.match(media.alt,/campaign artwork by Rehmat Panjab$/);assert.equal(media.product,null);}assert.match(PRODUCT_MEDIA_MANIFEST.junoon.card,/junoon/);assert.doesNotMatch(PRODUCT_MEDIA_MANIFEST.junoon.card,/nazakat/);assert.match(PRODUCT_MEDIA_MANIFEST.nazakat.card,/nazakat/);assert.doesNotMatch(PRODUCT_MEDIA_MANIFEST.nazakat.card,/junoon/);assert.equal(mediaForSlug("missing"),null);});

function product(slug:string,overrides:Partial<StorefrontProduct>={}):StorefrontProduct{return {id:slug,databaseId:slug,number:slug==="archived"?"99":"01",name:slug==="musk-rizali"?"Musk Rizali":slug==="vanilla-musk"?"Vanilla Musk":"Archived",slug,subtitle:"",atmosphere:slug==="vanilla-musk"?"Warm vanilla. Soft musk.":"Clean musky fragrance for work",microDescription:"",summary:"",description:"",searchAliases:[],suitableFor:["Work","Everyday"],suitability:"unisex",suitabilityNote:null,positioning:null,notes:{top:["Bergamot"],heart:["White Musk"],base:["Soft Woods"]},journey:null,reviewsEnabled:true,scentFamily:"Musk",character:["Soft","Clean"],color:"#fff",image:"/x.webp",imageAlt:"campaign artwork",imageKind:"campaign",heroImage:"/x.webp",moodImage:"/x.webp",socialImage:"/x.webp",imagePending:false,campaignImage:null,campaignImageAlt:null,status:"active",featured:false,createdAt:null,variants:[{id:slug,sizeMl:6,sku:slug,pricePaise:slug==="vanilla-musk"?59900:49900,currency:"INR",enabled:true,availableQuantity:10,lowStockThreshold:2}],enabledSizes:[6],...overrides};}
const catalogue=[product("musk-rizali"),product("vanilla-musk"),product("archived",{status:"sold_out"}),product("empty",{variants:[{id:"e",sizeMl:6,sku:"e",pricePaise:39900,currency:"INR",enabled:true,availableQuantity:0,lowStockThreshold:2}]})];
test("guide grounds active recommendations in budget, availability and natural language",()=>{const reply=createGuideReply("I want something soft for work under ₹550 in 6 ml",catalogue);assert.ok(reply.products.length);assert.ok(reply.products.every(p=>p.variants.every(v=>v.pricePaise<=55000&&v.availableQuantity>0&&v.sizeMl===6)));assert.ok(reply.products.every(p=>p.slug!=="archived"&&p.slug!=="empty"));assert.equal(reply.source,"deterministic");});
test("guide supports comparison and one-to-five layering without invented ratios",()=>{const comparison=createGuideReply("Compare Musk Rizali and Vanilla Musk",catalogue);assert.deepEqual(comparison.products.map(p=>p.slug),["musk-rizali","vanilla-musk"]);const layer=createGuideReply("I want five oils I can layer",catalogue,{max:5});assert.equal(layer.layering,true);assert.ok(layer.products.length<=5);assert.match(layer.message,/no ratio or application order is claimed/i);});
test("input is bounded and sanitized",()=>{const clean=sanitizeGuideInput(`<script>alert(1)</script>${"x".repeat(500)}`);assert.doesNotMatch(clean,/<|>/);assert.ok(clean.length<=360);});
test("public guide has rate limiting, keyboard controls, mobile drawer and WhatsApp handoff",()=>{const route=readFileSync("app/api/rehmat-guide/route.ts","utf8"),ui=readFileSync("app/components/rehmat-guide.tsx","utf8"),css=readFileSync("app/globals.css","utf8");assert.match(route,/register_experience_attempt/);assert.match(route,/FRAGRANCE_AI_PROVIDER/);assert.match(route,/return fallback/);assert.match(ui,/event\.key==="Escape"/);assert.match(ui,/aria-modal="true"/);assert.match(ui,/wa\.me/);assert.match(css,/@media\(max-width:700px\).*guide-panel/);});
