import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("India SEO collections and four guides are index-ready without city doorway pages",async()=>{const [collections,guides,sitemap]=await Promise.all([read("lib/search-collections.ts"),read("lib/guides.ts"),read("app/sitemap.ts")]);for(const slug of ["attar-perfume-oils","oud-perfume-oils","musk-perfume-oils","floral-perfume-oils","fruity-perfume-oils","unisex-perfume-oils","perfume-oil-gifts"])assert.match(collections,new RegExp(slug));for(const slug of ["perfume-oil-vs-spray-perfume","how-to-apply-attar-perfume-oil","understanding-fragrance-notes","choose-oud-musk-floral-fruity-perfume-oil"])assert.match(guides,new RegExp(slug));assert.match(sitemap,/searchCollections/);assert.match(sitemap,/guides\.map/);assert.doesNotMatch(`${collections}\n${guides}`,/delhi-attar|mumbai-attar|city collection/i);});

test("business identity, phone links and preview indexing are normalized",async()=>{const [merchant,contact,home,seo,robots]=await Promise.all([read("lib/merchant.ts"),read("app/contact/page.tsx"),read("app/page.tsx"),read("lib/seo.ts"),read("app/robots.ts")]);for(const source of [merchant,contact,home])assert.doesNotMatch(source,/98769 13550|9876913550|70094 66475|917009466475/);assert.match(merchant,/\+91 70094 64475/);assert.match(merchant,/917009464475/);assert.match(contact,/wa\.me\/\$\{merchant\.whatsapp\}/);assert.match(home,/PostalAddress/);assert.match(seo,/VERCEL_ENV==="preview"/);assert.match(robots,/disallow:"\/"/);});

test("policy release preserves history and keeps payment and courier providers inactive",async()=>{const [migration,commerce,shiprocket]=await Promise.all([read("supabase/migrations/202609220001_seo_geo_policy_release.sql"),read("lib/commerce.ts"),read("lib/shiprocket.ts")]);assert.match(migration,/policy_version='2026-09-22\.1'/);assert.match(migration,/insert into public\.store_policy_versions/);assert.match(migration,/publish_status='published'/);assert.match(migration,/₹1,000/);assert.match(migration,/whatsapp_number='917009464475'/);assert.match(commerce,/RAZORPAY_CHECKOUT_ENABLED = COMMERCE_ENABLED && RAZORPAY_ENABLED/);assert.match(shiprocket,/inactive until KYC/);});

test("Merchant Center feed uses authoritative products and no fabricated free shipping",async()=>{const feed=await read("app/google-merchant-feed.xml/route.ts");for(const field of ["g:id","g:item_group_id","g:image_link","g:price","g:availability","g:condition","g:brand","g:size","g:shipping_label","g:return_policy_label"])assert.match(feed,new RegExp(field));assert.doesNotMatch(feed,/<g:price>0 INR<\/g:price>/);assert.match(feed,/x-robots-tag/);});
