import type {SupabaseClient} from "@supabase/supabase-js";
import {NextResponse} from "next/server";
import {z} from "zod";
import {deliveryAddressSchema} from "../../../lib/address";
import {createSupabaseServerClient} from "../../../lib/supabase/server";

const idSchema=z.string().uuid();
async function viewer(){const raw=await createSupabaseServerClient();if(!raw)return null;const client=raw as unknown as SupabaseClient;const {data}=await client.auth.getUser();return data.user?{client,user:data.user}:null;}

export async function GET(){const auth=await viewer();if(!auth)return NextResponse.json({message:"Sign in to view saved addresses."},{status:401});const {data,error}=await auth.client.from("customer_addresses").select("*").eq("user_id",auth.user.id).order("is_default",{ascending:false}).order("created_at");return error?NextResponse.json({message:"Addresses could not be loaded."},{status:500}):NextResponse.json({addresses:data??[]});}

export async function POST(request:Request){const auth=await viewer();if(!auth)return NextResponse.json({message:"Sign in to save an address."},{status:401});const body=await request.json().catch(()=>null);const parsed=z.object({address:deliveryAddressSchema,isDefault:z.boolean().default(false)}).strict().safeParse(body);if(!parsed.success)return NextResponse.json({message:parsed.error.issues[0]?.message??"Check the address."},{status:400});const {address,isDefault}=parsed.data;if(isDefault)await auth.client.from("customer_addresses").update({is_default:false}).eq("user_id",auth.user.id);const {data,error}=await auth.client.from("customer_addresses").insert({user_id:auth.user.id,recipient_name:address.recipientName,mobile:address.mobile,alternate_mobile:address.alternateMobile||null,email:address.email,house:address.house,street_village:address.streetVillage,locality:address.locality,landmark:address.landmark||null,city:address.city,district:address.district,state:address.state,pin_code:address.pinCode,country:"India",address_type:address.addressType,instructions:address.instructions||null,is_default:isDefault}).select("*").single();return error?NextResponse.json({message:"Address could not be saved."},{status:409}):NextResponse.json({address:data});}

export async function PATCH(request:Request){const auth=await viewer();if(!auth)return NextResponse.json({message:"Sign in to update an address."},{status:401});const parsed=z.object({id:idSchema,isDefault:z.literal(true)}).strict().safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the address selection."},{status:400});await auth.client.from("customer_addresses").update({is_default:false}).eq("user_id",auth.user.id);const {error}=await auth.client.from("customer_addresses").update({is_default:true}).eq("id",parsed.data.id).eq("user_id",auth.user.id);return error?NextResponse.json({message:"Default address could not be changed."},{status:409}):NextResponse.json({message:"Default address updated."});}

export async function DELETE(request:Request){const auth=await viewer();if(!auth)return NextResponse.json({message:"Sign in to remove an address."},{status:401});const parsed=z.object({id:idSchema}).strict().safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the address selection."},{status:400});const {error}=await auth.client.from("customer_addresses").delete().eq("id",parsed.data.id).eq("user_id",auth.user.id);return error?NextResponse.json({message:"Address could not be removed."},{status:409}):NextResponse.json({message:"Address removed."});}
