"use client";

import { FormEvent, useState } from "react";

type ProductDraft = { id: string; product_number: string; name: string; slug: string; status: string; subtitle?: string | null; description?: string | null };

export function AdminProductForm({ initial }: { initial?: ProductDraft }) {
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("loading"); const form = new FormData(event.currentTarget); const payload = { ...Object.fromEntries(form.entries()), id: initial?.id }; try { const response = await fetch("/api/admin/products", { method: initial ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message); setState("success"); setMessage(initial ? "Product updated." : "Draft saved."); if (!initial) event.currentTarget.reset(); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t save that yet."); } }
  return <form className="admin-form" onSubmit={submit}><div><label htmlFor="product-number">Product number</label><input id="product-number" name="productNumber" maxLength={3} required defaultValue={initial?.product_number} /></div><div><label htmlFor="product-name">Name</label><input id="product-name" name="name" required defaultValue={initial?.name} /></div><div><label htmlFor="product-slug">Slug</label><input id="product-slug" name="slug" pattern="[a-z0-9-]+" required defaultValue={initial?.slug} /></div><div><label htmlFor="product-status">Status</label><select id="product-status" name="status" defaultValue={initial?.status ?? "draft"}><option value="draft">Draft</option><option value="coming_soon">Coming soon</option><option value="active">Active</option><option value="sold_out">Sold out</option><option value="archived">Archived</option></select></div><div className="full"><label htmlFor="product-subtitle">Subtitle</label><input id="product-subtitle" name="subtitle" defaultValue={initial?.subtitle ?? ""} /></div><div className="full"><label htmlFor="product-description">Description</label><textarea id="product-description" name="description" rows={6} defaultValue={initial?.description ?? ""} /></div><p className={`form-message ${state}`} aria-live="polite">{message}</p><button className="button button-dark" type="submit" disabled={state === "loading"}>{state === "loading" ? "Saving…" : initial ? "Update product" : "Save draft"}</button></form>;
}
