"use client";
import {useMemo,useState} from "react";
import {settingsFields,type SettingsGroup,type StoreSettings} from "../../../lib/store-settings-schema";
const titles:Record<SettingsGroup,string>={merchant:"Merchant",shipping:"Shipping",cancellation:"Cancellation",returns:"Returns",privacy:"Privacy",terms:"Terms"};
const label=(value:string)=>value.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());
type Checks={email:boolean;phone:boolean;shipping:boolean;courier:boolean};
export function PolicySettingsForm({initial,published,notes,version,effectiveDate,checks}:{initial:StoreSettings;published:boolean;notes:string;version:string;effectiveDate:string;checks:Checks}){
  const [message,setMessage]=useState(""),[preview,setPreview]=useState(false);
  const ready=useMemo(()=>Object.values(checks).every(Boolean),[checks]);
  async function submit(formData:FormData){setMessage("Saving…");const groups={} as StoreSettings;for(const group of Object.keys(settingsFields) as SettingsGroup[])groups[group]=Object.fromEntries(settingsFields[group].map(field=>[field,String(formData.get(`${group}.${field}`)||"").trim()]));const response=await fetch("/api/admin/policies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groups,publish:formData.has("publish"),publishConfirmation:formData.has("publishConfirmation"),policyVersion:String(formData.get("policyVersion")||"").trim(),effectiveDate:String(formData.get("effectiveDate")||""),adminNotes:String(formData.get("adminNotes")||"")})});const result=await response.json();setMessage(result.message);}
  return <><form className="policy-settings-form" action={submit}>{(Object.keys(settingsFields) as SettingsGroup[]).map(group=><fieldset key={group}><legend>{titles[group]}</legend><div className="admin-form">{settingsFields[group].map(field=><label className={group==="merchant"?undefined:"full"} key={field}>{label(field)}{field.toLowerCase().includes("date")?<input type="date" name={`${group}.${field}`} defaultValue={initial[group][field]||""}/>:<textarea rows={group==="merchant"?2:3} name={`${group}.${field}`} defaultValue={initial[group][field]||""}/>}</label>)}</div></fieldset>)}<fieldset><legend>Version and publishing</legend><div className="admin-form"><label>Policy version<input name="policyVersion" defaultValue={version} required/></label><label>Effective date<input type="date" name="effectiveDate" defaultValue={effectiveDate} required/></label></div><div className="policy-readiness" aria-label="Publication checks"><span data-ready={checks.email}>Support mailbox send and receive</span><span data-ready={checks.phone}>Support phone confirmed</span><span data-ready={checks.shipping}>Shipping calculation verified</span><span data-ready={checks.courier}>Courier production configuration</span></div><label><input name="publish" type="checkbox" defaultChecked={published} disabled={!ready}/> Publish this version</label><label><input name="publishConfirmation" type="checkbox" disabled={!ready}/> I confirm the preview and publication checks</label><label className="full">Private admin notes<textarea name="adminNotes" rows={4} defaultValue={notes}/></label></fieldset><div className="admin-form-actions"><button className="button button-outline" type="button" onClick={()=>setPreview(value=>!value)} aria-expanded={preview}>Preview structured values</button><button className="button button-dark" type="submit">Save policy draft</button></div><p role="status">{message}</p></form>{preview&&<section className="policy-admin-preview"><p className="eyebrow">Draft preview · {version}</p>{(Object.keys(settingsFields) as SettingsGroup[]).map(group=><details key={group} open={group==="merchant"}><summary>{titles[group]}</summary><dl>{settingsFields[group].map(field=><div key={field}><dt>{label(field)}</dt><dd>{initial[group][field]||"Not supplied"}</dd></div>)}</dl></details>)}</section>}</>;
}
