export type Guide={slug:string;title:string;description:string;updated:string;sections:{heading:string;paragraphs:string[];bullets?:string[]}[];faqs:{question:string;answer:string}[];collections:{href:string;label:string}[]};

export const guides:Guide[]=[
  {slug:"perfume-oil-vs-spray-perfume",title:"Perfume Oil vs Spray Perfume",description:"Understand how concentrated perfume oil differs from spray perfume in application, scent character and everyday use.",updated:"2026-09-22",collections:[{href:"/collection/attar-perfume-oils",label:"Explore attar and perfume oils"},{href:"/collection/unisex-perfume-oils",label:"Browse unisex perfume oils"}],sections:[
    {heading:"The practical difference",paragraphs:["Perfume oil is applied directly and sparingly, usually to pulse points. Spray perfume disperses fragrance through a fine mist. The format changes how a fragrance is applied and experienced, but neither format is automatically better for every person or occasion.","Rehmat Panjab offers concentrated perfume oils. They are designed for a close-to-skin fragrance experience; performance varies with skin, climate, storage and application."]},
    {heading:"Scent and projection",paragraphs:["Oil often feels intimate because it stays close to the areas where it is applied. A spray can create a broader cloud because its droplets travel through the air. Formula, concentration and individual skin chemistry matter more than a simple oil-versus-spray rule."]},
    {heading:"Choosing a format",paragraphs:["Choose perfume oil when you enjoy precise application, a compact bottle and a personal scent ritual. Choose a spray when you prefer wider distribution across clothing or the air around you. Test carefully if you are unsure, and avoid assuming that one format guarantees a fixed number of hours."],bullets:["Consider how closely you want the fragrance to sit.","Think about where and how often you will reapply.","Choose notes and mood before choosing by marketing labels alone."]},
  ],faqs:[{question:"Is perfume oil stronger than spray perfume?",answer:"Not always. Strength depends on the formula, amount applied, skin, climate and other factors."},{question:"Can perfume oil be sprayed?",answer:"Use the applicator supplied for the product. Rehmat Panjab perfume oils are intended for controlled direct application unless a product states otherwise."}]},
  {slug:"how-to-apply-attar-perfume-oil",title:"How to Apply Attar and Perfume Oil",description:"A simple guide to applying concentrated attar and perfume oil carefully on skin and clothing.",updated:"2026-09-22",collections:[{href:"/collection/attar-perfume-oils",label:"Browse concentrated perfume oils"},{href:"/collection/perfume-oil-gifts",label:"Explore perfume-oil gifts"}],sections:[
    {heading:"Start with a small amount",paragraphs:["Use a small, controlled touch on clean skin. Perfume oil is concentrated, so begin lightly and add only if needed. Avoid rubbing the application point aggressively; allow the fragrance to settle and develop."]},
    {heading:"Choose application points",paragraphs:["Wrists and the sides of the neck are common pulse points. Apply only to healthy, unbroken skin and keep perfume oil away from eyes and other sensitive areas. If you have sensitivities, review the product information and seek appropriate professional advice before use."]},
    {heading:"Skin, clothing and storage",paragraphs:["Fabric can hold scent differently from skin and some oils may mark delicate or pale materials. Test an inconspicuous area first and avoid jewellery or surfaces that may stain.","Keep the bottle closed, upright and away from strong heat and direct sunlight. A stable storage place helps preserve the fragrance character."],bullets:["Apply sparingly.","Let each stage unfold before adding more.","Store the bottle securely and out of children’s reach."]},
  ],faqs:[{question:"Where should I apply attar?",answer:"Pulse points such as the wrists or sides of the neck are common choices, provided the skin is healthy and comfortable."},{question:"Should I rub my wrists together?",answer:"Gentle application is enough. Allowing the oil to settle avoids unnecessary friction."}]},
  {slug:"understanding-fragrance-notes",title:"Understanding Top, Heart and Base Notes",description:"Learn how top, heart and base notes describe the evolving stages of a perfume-oil composition.",updated:"2026-09-22",collections:[{href:"/collection",label:"Compare verified fragrance notes"},{href:"/find-your-scent",label:"Find a scent by mood and notes"}],sections:[
    {heading:"Top notes: the opening",paragraphs:["Top notes describe the first recognisable impression after application. Citrus, light spices and bright fruits often appear here, but a note’s placement depends on the composition. The opening is an introduction rather than the whole fragrance."]},
    {heading:"Heart notes: the character",paragraphs:["Heart notes become clearer as the opening settles. Florals, spices, fruits and textured accords often shape this central stage. On a product page, the Heart group should be read separately from the Top group rather than treating every listed material as a top note."]},
    {heading:"Base notes: the drydown",paragraphs:["Base notes support the later stage of the fragrance. Woods, amber, musk, vanilla and oud frequently appear here. Development varies by skin, temperature and application, so a note pyramid is a useful map, not an exact timetable."],bullets:["Read all three note groups.","Use the scent journey to understand transitions.","Compare families and mood as well as individual ingredients."]},
  ],faqs:[{question:"Are fragrance notes the same as ingredients?",answer:"No. Notes describe perceived scent character and do not necessarily identify every material in a formula."},{question:"Why does a fragrance smell different later?",answer:"Different parts of the composition become more or less noticeable as the fragrance settles on skin."}]},
  {slug:"choose-oud-musk-floral-fruity-perfume-oil",title:"How to Choose Oud, Musk, Floral or Fruity Perfume Oil",description:"Choose a perfume-oil family by atmosphere, notes and occasion without relying on rigid gender rules.",updated:"2026-09-22",collections:[{href:"/collection/oud-perfume-oils",label:"Oud perfume oils"},{href:"/collection/musk-perfume-oils",label:"Musk perfume oils"},{href:"/collection/floral-perfume-oils",label:"Floral perfume oils"},{href:"/collection/fruity-perfume-oils",label:"Fruity perfume oils"}],sections:[
    {heading:"Begin with atmosphere",paragraphs:["Ask whether you want something deep, clean, soft, bright, sweet or floral. Mood is often a more useful starting point than a strict label. Rehmat Guide and the collection filters can help narrow the current catalogue using verified product facts."]},
    {heading:"Oud and musk",paragraphs:["Oud-led fragrances often feel woody, deep or resinous, especially beside rose, amber or spice. Musk can feel clean, soft, velvety or warm depending on the surrounding notes. Neither family belongs to one gender or one occasion."]},
    {heading:"Floral and fruity",paragraphs:["Floral perfume oils can move from luminous jasmine to darker rose. Fruity profiles can feel fresh, tart, juicy or gourmand before settling into musk, amber, woods or vanilla.","Look at the full Top, Heart and Base groups. A single fruit or flower in the opening does not define the entire drydown."],bullets:["For depth, explore oud, amber and woods.","For softness, explore musk, vanilla and gentle florals.","For brightness, explore citrus, berries and other fruit notes.","For gifting, use the recipient’s known preferences rather than assumptions."]},
  ],faqs:[{question:"Are oud fragrances only for evenings?",answer:"No. Composition and personal preference matter. Cleaner or softer oud styles may suit many settings."},{question:"Can perfume oils be unisex?",answer:"Yes. Rehmat Panjab treats suitability as guidance and encourages choosing by notes, mood and personal preference."}]},
];
