import type {StoreSettings} from "./store-settings-schema";

export const POLICY_VERSION="2026-09-10.2";
export const POLICY_DATE="September 10, 2026";
export const policySlugs=["shipping","returns","terms","privacy"] as const;
export type PolicySlug=(typeof policySlugs)[number];
export type PolicySection={heading:string;paragraphs:string[];bullets?:string[]};
export type PolicyTemplate={title:string;description:string;sections:PolicySection[]};

const legalOverride="These terms do not exclude rights or remedies that cannot legally be limited. If a policy term conflicts with mandatory law, applicable law prevails.";

export function getPolicyTemplate(slug:PolicySlug,settings:StoreSettings):PolicyTemplate{
  const merchant=settings.merchant;
  const contact=`Email: ${merchant.supportEmail}. Phone: ${merchant.supportPhone}. Hours: ${merchant.supportHours}.`;
  const shipping:PolicyTemplate={title:"Shipping Policy",description:"How Rehmat Panjab processes and delivers orders within India.",sections:[
    {heading:"Order processing",paragraphs:["Rehmat Panjab currently accepts and delivers orders within India only. Cash on Delivery is not available.","Confirmed orders are normally prepared and dispatched within 1–2 business days. Processing may take longer during public holidays, unusually high order volumes, address-verification issues or circumstances outside our reasonable control.","Orders placed through WhatsApp remain order requests until Rehmat Panjab confirms the products, price, delivery address and payment."]},
    {heading:"Delivery estimates",paragraphs:["After dispatch, delivery is normally expected within 3–7 business days. Delivery times are estimates rather than guarantees and may vary by destination, courier operations, weather, public holidays, transport disruption and other circumstances outside our control."]},
    {heading:"Shipping charges",paragraphs:["Orders with an eligible merchandise subtotal of ₹1,500 or more receive free standard shipping. Eligibility is calculated after product discounts and coupons, excluding shipping charges.","Shipping charges apply below ₹1,500. Share your order request on WhatsApp and Rehmat Panjab will confirm the courier charge before payment.","Coupons do not reduce shipping charges unless an offer expressly states otherwise."]},
    {heading:"Tracking",paragraphs:["When tracking is available, Rehmat Panjab will send shipment or tracking information using the customer’s provided email address, phone number, WhatsApp number or another available order-contact method.","Courier delivery may be arranged manually. No active shipping-platform integration is represented until onboarding and production verification are complete."]},
    {heading:"Address accuracy and changes",paragraphs:["Customers are responsible for providing a complete and accurate name, phone number, postal code and delivery address.","An address-change request must be submitted within 12 hours of ordering and before dispatch. We cannot guarantee a change after an order has been packed, handed to a courier or dispatched.","Additional charges caused by an incorrect or incomplete address may be payable by the customer."]},
    {heading:"Failed delivery",paragraphs:["If delivery fails because the customer is unavailable, refuses delivery, provides an incorrect address or does not respond to the courier, the parcel may be returned to Rehmat Panjab.","Failed deliveries and any reshipment request are reviewed manually. Return-to-origin charges are not deducted automatically."]},
    {heading:"Delays or lost shipments",paragraphs:["If tracking has not updated for an unusual period or a parcel appears lost, contact us with the order number. We will raise the matter with the courier and provide an update after receiving available information."]},
    {heading:"Damaged packages",paragraphs:["If a parcel arrives visibly damaged, leaking or contains an incorrect product, record a clear, continuous unboxing video before opening or removing the contents. Contact Rehmat Panjab as soon as possible, preferably within four hours of recorded delivery, and provide the order number, video and clear photographs.","This reporting target helps us investigate courier and packing issues quickly. It does not exclude rights that cannot legally be limited."]},
    {heading:"Contact",paragraphs:[contact,legalOverride]},
  ]};
  const returns:PolicyTemplate={title:"Cancellation, Return and Refund Policy",description:"Cancellation, damage, incorrect-item and refund terms for Rehmat Panjab orders.",sections:[
    {heading:"Order cancellation",paragraphs:["A customer may request cancellation within 12 hours of placing the order, provided the order has not already been packed, processed for dispatch or handed to the courier.","A cancellation request is not final until confirmed by Rehmat Panjab.","Once an order has been dispatched, it cannot ordinarily be cancelled. The customer may still contact us if the order is damaged, incorrect, lost or affected by another verified fulfilment problem."]},
    {heading:"No change-of-mind returns",paragraphs:["Rehmat Panjab does not accept returns, exchanges or refunds after delivery merely because:"],bullets:["The customer changed their mind.","The customer no longer wants the product.","The fragrance differs from personal expectations or preferences.","The customer selected the wrong product or bottle size.","The product has been opened or used."]},
    {heading:"Fragrance expectations",paragraphs:["Fragrance perception and performance can vary between people, skin types, climates and methods of application. Product descriptions and Rehmat Guide recommendations provide guidance and are not guarantees of personal preference.","This restriction does not apply where a customer has received a verified damaged, leaking, defective or incorrect item or where applicable law requires another remedy."]},
    {heading:"Damaged, leaking, defective or incorrect items",paragraphs:["Contact Rehmat Panjab as soon as possible, preferably within four hours of recorded delivery.","The product and original packaging should be retained until the review is complete.","Claims are assessed using supplied evidence, order records, inventory records and available courier information. False, altered or incomplete claims may be rejected where legally permitted."],bullets:["Order number","Clear, continuous unboxing video","Photographs showing the packaging, shipping label and affected product","A short description of the issue"]},
    {heading:"Resolution",paragraphs:["For an approved damaged, defective or incorrect-item claim, the customer may choose a replacement of the affected item, subject to stock availability, or a refund of the approved product amount.","If a replacement is unavailable, an eligible refund will be offered. Rehmat Panjab will provide instructions if the affected item must be returned. Customers should not send products back without authorization."]},
    {heading:"Refund processing",paragraphs:["Approved refunds will be initiated within two business days.","The customer’s bank, card issuer, UPI provider or payment service may require additional time to credit the amount. This external processing time is outside Rehmat Panjab’s direct control.","Refunds will ordinarily be issued to the original payment method. Original shipping charges are non-refundable except where applicable law requires otherwise or Rehmat Panjab confirms another resolution."]},
    {heading:"Coupon adjustments",paragraphs:["Where an order used coupon NEW or another discount, any approved refund will be based on the amount actually paid for the affected product after discount.","Coupon eligibility is not automatically restored following cancellation or refund. Rehmat Panjab may restore eligibility after reviewing the order."]},
    {heading:"Contact",paragraphs:[contact,legalOverride]},
  ]};
  const terms:PolicyTemplate={title:"Terms and Conditions",description:"Terms governing the Rehmat Panjab website and customer orders.",sections:[
    {heading:"Merchant information",paragraphs:[`Rehmat Panjab is operated by Harkirat Singh from ${merchant.businessAddress}. ${contact}`]},
    {heading:"Eligibility",paragraphs:["Customers must be legally capable of entering into a purchase contract and must provide accurate order and contact information."]},
    {heading:"Product information",paragraphs:["We aim to present product names, bottle sizes, notes, prices, descriptions, images and availability accurately. Screen colours, fragrance perception and product presentation may vary.","Fragrance notes describe scent character and do not necessarily identify every material used in a formulation.","Performance varies according to skin, climate, storage and application. Rehmat Panjab does not guarantee a fixed number of performance hours unless expressly stated using approved evidence."]},
    {heading:"Inspiration references",paragraphs:["Certain products may include a secondary reference to a fragrance that inspired their scent direction.","References to inspiration fragrances describe scent direction only. Rehmat Panjab is independent and is not affiliated with, endorsed by or licensed by the owners of those fragrances.","JUNOON, NAZAKAT, GULNAAR and AFSOON remain the primary Rehmat Panjab product names wherever inspiration references appear."]},
    {heading:"Prices and availability",paragraphs:["All displayed prices are in Indian rupees unless stated otherwise.","Prices, offers and availability may change before an order is confirmed. The price recorded by Rehmat Panjab’s server at checkout or manual order confirmation is authoritative.","Submitting an order does not guarantee acceptance. Rehmat Panjab may decline or cancel an order because of stock errors, payment failure, pricing errors, suspected fraud, delivery limitations or another legitimate reason. Any captured payment for a cancelled order will be handled through the applicable refund process."]},
    {heading:"Online orders and payment",paragraphs:["When checkout is enabled after production verification, online payments are processed through Razorpay for Rehmat Panjab, operated by Harkirat Singh.","UPI, credit cards, debit cards, net banking and wallets are offered only when available in Razorpay Checkout. EMI, Pay Later, international payments and Cash on Delivery are not offered.","Public checkout remains unavailable until credential, webhook, controlled payment, email and refund verification are complete."]},
    {heading:"WhatsApp orders",paragraphs:["A WhatsApp message is an order request, not an accepted order. The order becomes confirmed only after Rehmat Panjab verifies availability, price, discount, shipping details and payment.","WhatsApp ordering is not described as completed checkout before confirmation."]},
    {heading:"Coupons and discounts",paragraphs:["Coupon NEW provides an eligible first-time customer 15% off their first completed purchase.","Eligibility is determined using normalized customer information and verified order history. The offer is limited to one successful redemption per eligible customer."],bullets:["Coupons may have eligibility restrictions.","Coupons may exclude shipping.","Coupons may not be combined unless expressly permitted.","Coupons may be suspended in cases of misuse.","Coupons have no cash value.","Coupons must be validated by the server."]},
    {heading:"Inventory and order limits",paragraphs:["Customers cannot order more units than available inventory. Rehmat Panjab may apply reasonable quantity limits.","Inventory reduces only after verified payment and successful order recording. Failed or abandoned payments must not permanently reduce available stock."]},
    {heading:"Shipping, cancellations and refunds",paragraphs:["Shipping, cancellation, return and refund conditions form part of these Terms. Customers should review the applicable policies before ordering."]},
    {heading:"Appropriate use",paragraphs:["Customers must not interfere with website security or operation, manipulate prices, inventory or discounts, submit false orders or claims, abuse public endpoints, upload malicious content or infringe intellectual-property rights."]},
    {heading:"Intellectual property",paragraphs:["Rehmat Panjab’s branding, original product names, website content, graphics and other protected materials may not be copied or commercially reused without permission, except where permitted by law. Third-party names and trademarks belong to their respective owners."]},
    {heading:"Liability",paragraphs:["Nothing in these Terms excludes a right or remedy that cannot be excluded under applicable law.","To the extent legally permitted, Rehmat Panjab is not responsible for indirect losses caused by website interruption, courier delay, customer-provided address errors, unauthorized account access or circumstances outside reasonable control."]},
    {heading:"Governing law",paragraphs:["These Terms are governed by the laws of India. Subject to mandatory consumer rights and jurisdictional rules, disputes will be subject to the appropriate courts serving Samrala, Punjab."]},
    {heading:"Changes",paragraphs:["Rehmat Panjab may update these Terms prospectively. The version accepted or applicable when an order is placed will continue to govern that order, unless applicable law requires otherwise."]},
  ]};
  const privacy:PolicyTemplate={title:"Privacy Policy",description:"How Rehmat Panjab handles personal information.",sections:[
    {heading:"Information collected",paragraphs:["Depending on how a customer uses the service, Rehmat Panjab may collect the information listed below.","Complete public Rehmat Guide conversations are not stored by default.","Rehmat Panjab does not directly collect or store complete card numbers, UPI PINs or banking passwords through the website."],bullets:["Name","Phone number","Email address","Billing and delivery address","Order and product information","Payment status and transaction references","Coupon eligibility and redemption information","Customer-support communications","Reviews or feedback submitted by the customer","Technical information such as browser, device, IP address, logs and cookie preferences","Rehmat Guide interaction events where needed for operation, security or privacy-conscious analytics"]},
    {heading:"Purposes of processing",paragraphs:["Information may be used only as reasonably needed for the purposes below."],bullets:["Process and deliver orders","Confirm payments and provide tracking","Respond to support requests","Handle cancellations, damage claims and refunds","Verify first-purchase coupon eligibility","Prevent fraud and misuse and maintain website security","Comply with legal, tax, accounting and dispute-handling obligations","Improve website performance using appropriately configured analytics","Send marketing only with valid optional consent"]},
    {heading:"Service providers",paragraphs:["Information may be shared only as reasonably necessary with providers actually supporting the transaction or website.","When generative guidance is available, a server-side language-model provider may process the customer’s redacted Rehmat Guide message to produce fragrance guidance. Complete conversations are not stored by default, and contact, address, order, payment and authentication details are removed before a provider request."],bullets:["Supabase for database, authentication and storage services","Vercel for website hosting and delivery","A language-model inference provider for optional Rehmat Guide responses","Razorpay when an enabled online payment is initiated","WhatsApp or Meta when the customer chooses WhatsApp communication"]},
    {heading:"Payment information",paragraphs:["When online checkout is enabled, Razorpay receives payment and transaction information necessary to process the payment. Rehmat Panjab does not directly receive or store complete card numbers, UPI PINs or banking passwords."]},
    {heading:"Cookies and analytics",paragraphs:["Only cookies or storage necessary for website operation are used until an accurate consent interface exists. Non-essential marketing or behavioural analytics must not load before valid consent where consent is required. Visitors can accept, reject and change non-essential cookie preferences."]},
    {heading:"Data retention",paragraphs:["Personal information is retained only for as long as reasonably necessary for order fulfilment, support, fraud prevention, legal compliance, accounting and dispute resolution. Retention periods are documented by data category rather than represented as one universal period."]},
    {heading:"Customer rights and requests",paragraphs:[`Customers may contact Rehmat Panjab at ${merchant.supportEmail} to request access, correction, updating or deletion of personal information, or to withdraw optional marketing consent, subject to information that must be retained for legal, accounting, fraud-prevention or dispute purposes. Rehmat Panjab may take reasonable steps to verify the requester’s identity.`]},
    {heading:"Security",paragraphs:["Rehmat Panjab uses reasonable administrative and technical safeguards intended to protect personal information. No internet or storage system can be guaranteed completely secure."]},
    {heading:"Children",paragraphs:["The website is not intended to knowingly collect unnecessary personal information from children. If age-specific consent requirements apply, an appropriate process will be implemented."]},
    {heading:"International processing",paragraphs:["Some technology providers may process information outside the customer’s state or outside India according to their infrastructure and contractual arrangements. More specific transfer claims will be published only after the providers’ current data-processing terms are verified."]},
    {heading:"Policy changes",paragraphs:["Material changes will be reflected through an updated date and, where appropriate, an additional notice. Existing order records retain the policy version accepted at purchase."]},
    {heading:"Privacy contact",paragraphs:[`Rehmat Panjab is operated by Harkirat Singh from ${merchant.businessAddress}. ${contact}`,legalOverride]},
  ]};
  return {shipping,returns,terms,privacy}[slug];
}
