import type {SupabaseClient} from "@supabase/supabase-js";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireAdmin} from "../../../../lib/supabase/auth";

const nullableText=z.preprocess(value=>value===""?null:value,z.string().trim().max(1000).nullable());
const nullableNumber=z.preprocess(value=>value===""||value===null?null:value,z.coerce.number().min(0).max(100000000).nullable());
const schema=z.object({id:z.uuid().optional(),name:z.string().trim().min(1).max(120),internalCode:nullableText,volumeMl:z.coerce.number().positive().max(1000),publicLabel:nullableText,shortDescription:nullableText,photoPath:nullableText,thumbnailPath:nullableText,altText:nullableText,material:nullableText,applicatorType:nullableText,colour:nullableText,dimensions:nullableText,emptyWeightGrams:nullableNumber,packagingBoxId:z.preprocess(value=>value===""?null:value,z.uuid().nullable()),packagingCostPaise:nullableNumber,bottleCostPaise:nullableNumber,availablePackagingQuantity:z.preprocess(value=>value===""?null:value,z.coerce.number().int().min(0).nullable()),lowStockThreshold:z.preprocess(value=>value===""?null:value,z.coerce.number().int().min(0).nullable()),status:z.enum(["active","inactive"]),displayOrder:z.coerce.number().int().min(0).max(10000),adminNotes:nullableText}).strict();

export async function POST(request:Request){const {supabase,user,role}=await requireAdmin();if(role!=="super_admin")return NextResponse.json({message:"Super-admin access required."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:parsed.error.issues[0]?.message||"Check the bottle fields."},{status:400});const value=parsed.data;const payload={name:value.name,internal_code:value.internalCode,volume_ml:value.volumeMl,public_label:value.publicLabel,short_description:value.shortDescription,photo_path:value.photoPath,thumbnail_path:value.thumbnailPath,alt_text:value.altText,material:value.material,applicator_type:value.applicatorType,colour:value.colour,dimensions:value.dimensions,empty_weight_grams:value.emptyWeightGrams,packaging_box_id:value.packagingBoxId,packaging_cost_paise:value.packagingCostPaise,bottle_cost_paise:value.bottleCostPaise,available_packaging_quantity:value.availablePackagingQuantity,low_stock_threshold:value.lowStockThreshold,status:value.status,display_order:value.displayOrder,admin_notes:value.adminNotes,archived_at:null,updated_at:new Date().toISOString()};const db=supabase as unknown as SupabaseClient;const query=value.id?db.from("bottles").update(payload).eq("id",value.id):db.from("bottles").insert(payload);const {data,error}=await query.select("*").single();if(error)return NextResponse.json({message:"Bottle could not be saved. Check the internal code and relationships."},{status:409});await db.from("audit_logs").insert({actor_id:user.id,action:value.id?"bottle.updated":"bottle.created",entity_type:"bottle",entity_id:data.id,metadata:{volume_ml:value.volumeMl}});return NextResponse.json({message:"Bottle saved.",item:data});}

export async function PATCH(request:Request){const {supabase,user,role}=await requireAdmin();if(role!=="super_admin")return NextResponse.json({message:"Super-admin access required."},{status:403});const parsed=z.object({id:z.uuid()}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"A bottle id is required."},{status:400});const db=supabase as unknown as SupabaseClient;const {data:references}=await db.from("product_variants").select("id",{count:"exact",head:true}).eq("bottle_id",parsed.data.id);void references;const {error}=await db.from("bottles").update({status:"archived",archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",parsed.data.id);if(error)return NextResponse.json({message:"Bottle could not be archived."},{status:409});await db.from("audit_logs").insert({actor_id:user.id,action:"bottle.archived",entity_type:"bottle",entity_id:parsed.data.id,metadata:{archive_only:true}});return NextResponse.json({message:"Bottle archived; product and order references were preserved."});}
