"use client";
import { useState } from "react";

const lines=(value:unknown)=>Array.isArray(value)?value.join("\n"):"";
export function ExperienceForm({initial}:{initial:Record<string,unknown>}){
  const [message,setMessage]=useState("");
  async function submit(formData:FormData){ setMessage("Saving…"); const body=Object.fromEntries(formData); const response=await fetch("/api/admin/experiences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,layeringEnabled:formData.has("layeringEnabled"),quizEnabled:formData.has("quizEnabled"),whatsappEnabled:formData.has("whatsappEnabled"),guideEnabled:formData.has("guideEnabled"),guideDeterministicFallback:formData.has("guideDeterministicFallback")})}); const result=await response.json().catch(()=>({message:"Could not save settings."})); setMessage(result.message); }
  return <form className="admin-form experience-admin-form" action={submit}>
    <div className="full"><p className="eyebrow">Rehmat Guide</p><h2>Conversational adviser</h2><p>Preview: {String(initial.guide_greeting??"Sat Sri Akal. I’m your Rehmat Guide. Tell me what you would like your fragrance to feel like.")}</p></div>
    <label><input type="checkbox" name="guideEnabled" defaultChecked={initial.guide_enabled===undefined||Boolean(initial.guide_enabled)}/> Rehmat Guide enabled</label><label>Maximum recommendations<input name="guideMaxRecommendations" type="number" min="1" max="5" defaultValue={Number(initial.guide_max_recommendations??3)}/></label>
    <label className="full">Greeting<textarea name="guideGreeting" rows={3} defaultValue={String(initial.guide_greeting??"Sat Sri Akal. I’m your Rehmat Guide. Tell me what you would like your fragrance to feel like.")}/></label><label className="full">Starter prompts, one per line<textarea name="guidePrompts" rows={5} defaultValue={lines(initial.guide_prompts)}/></label>
    <label>Allowed product slugs (blank means all)<textarea name="guideAllowedProducts" rows={5} defaultValue={lines(initial.guide_allowed_products)}/></label><label>Excluded product slugs<textarea name="guideExcludedProducts" rows={5} defaultValue={lines(initial.guide_excluded_products)}/></label>
    <label className="full">Approved facts<textarea name="guideApprovedFacts" rows={4} defaultValue={String(initial.guide_approved_facts??"")}/></label><label className="full">Approved layering guidance<textarea name="guideLayeringGuidance" rows={4} defaultValue={String(initial.guide_layering_guidance??"")}/></label>
    <label>Safety response<textarea name="guideSafetyResponse" rows={4} defaultValue={String(initial.guide_safety_response??"I can offer fragrance guidance, but not medical or allergy guarantees.")}/></label><label>Escalation message<textarea name="guideEscalationMessage" rows={4} defaultValue={String(initial.guide_escalation_message??"For help with an order, please continue on WhatsApp.")}/></label>
    <label>Provider<select name="guideProvider" defaultValue={String(initial.guide_provider??"deterministic")}><option value="deterministic">Deterministic (no paid API)</option><option value="custom">Configured server provider</option></select></label><label><input type="checkbox" name="guideDeterministicFallback" defaultChecked={initial.guide_deterministic_fallback===undefined||Boolean(initial.guide_deterministic_fallback)}/> Deterministic fallback</label><label>Requests per 10 minutes<input name="guideRateLimit" type="number" min="1" max="60" defaultValue={Number(initial.guide_rate_limit??12)}/></label>
    <label><input type="checkbox" name="layeringEnabled" defaultChecked={Boolean(initial.layering_enabled)}/> Layering Lab enabled</label><label>Maximum fragrances<input name="layeringMaxFragrances" type="number" min="2" max="5" defaultValue={Number(initial.layering_max_fragrances??5)}/></label>
    <label className="full">Featured prompts, one per line<textarea name="featuredPrompts" rows={8} defaultValue={lines(initial.featured_prompts)}/></label><label>Moods, one per line<textarea name="suggestedMoods" rows={6} defaultValue={lines(initial.suggested_moods)}/></label><label>Occasions, one per line<textarea name="suggestedOccasions" rows={6} defaultValue={lines(initial.suggested_occasions)}/></label><label className="full">Safety notice<textarea name="safetyNotice" rows={3} defaultValue={String(initial.safety_notice??"")}/></label><label className="full">Private adviser guidance<textarea name="systemGuidance" rows={6} defaultValue={String(initial.system_guidance??"")}/></label><label>Excluded product slugs<textarea name="productExclusions" rows={5} defaultValue={lines(initial.product_exclusions)}/></label><label>Incompatible pairs JSON<textarea name="incompatiblePairs" rows={5} defaultValue={JSON.stringify(initial.incompatible_pairs??[],null,2)}/></label>
    <label><input type="checkbox" name="quizEnabled" defaultChecked={Boolean(initial.quiz_enabled)}/> Name Your Rehmat enabled</label><label>Allowed portrait words<textarea name="portraitWords" rows={6} defaultValue={lines(initial.portrait_words)}/></label><label className="full">12-question configuration JSON<textarea name="quizQuestions" rows={12} defaultValue={JSON.stringify(initial.quiz_questions??[],null,2)}/></label>
    <label><input type="checkbox" name="whatsappEnabled" defaultChecked={Boolean(initial.whatsapp_enabled)}/> WhatsApp requests enabled</label><label>WhatsApp number<input name="whatsappNumber" inputMode="numeric" defaultValue={String(initial.whatsapp_number??"")}/></label><label className="full">Default request message<textarea name="whatsappDefaultMessage" rows={3} defaultValue={String(initial.whatsapp_default_message??"")}/></label><label className="full">Confirmation notice<textarea name="whatsappNotice" rows={3} defaultValue={String(initial.whatsapp_notice??"")}/></label>
    <button className="button button-dark" type="submit">Save settings</button><p className="form-message" role="status">{message}</p>
  </form>;
}
