"use client";
import { useState } from "react";

const lines=(value:unknown)=>Array.isArray(value)?value.join("\n"):"";
export function ExperienceForm({initial}:{initial:Record<string,unknown>}){
  const [message,setMessage]=useState("");
  async function submit(formData:FormData){ setMessage("Saving…"); const body=Object.fromEntries(formData); const response=await fetch("/api/admin/experiences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,layeringEnabled:formData.has("layeringEnabled"),quizEnabled:formData.has("quizEnabled"),whatsappEnabled:formData.has("whatsappEnabled")})}); const result=await response.json().catch(()=>({message:"Could not save settings."})); setMessage(result.message); }
  return <form className="admin-form experience-admin-form" action={submit}>
    <label><input type="checkbox" name="layeringEnabled" defaultChecked={Boolean(initial.layering_enabled)}/> Layering Lab enabled</label><label>Maximum fragrances<input name="layeringMaxFragrances" type="number" min="2" max="5" defaultValue={Number(initial.layering_max_fragrances??5)}/></label>
    <label className="full">Featured prompts, one per line<textarea name="featuredPrompts" rows={8} defaultValue={lines(initial.featured_prompts)}/></label><label>Moods, one per line<textarea name="suggestedMoods" rows={6} defaultValue={lines(initial.suggested_moods)}/></label><label>Occasions, one per line<textarea name="suggestedOccasions" rows={6} defaultValue={lines(initial.suggested_occasions)}/></label><label className="full">Safety notice<textarea name="safetyNotice" rows={3} defaultValue={String(initial.safety_notice??"")}/></label><label className="full">Private adviser guidance<textarea name="systemGuidance" rows={6} defaultValue={String(initial.system_guidance??"")}/></label><label>Excluded product slugs<textarea name="productExclusions" rows={5} defaultValue={lines(initial.product_exclusions)}/></label><label>Incompatible pairs JSON<textarea name="incompatiblePairs" rows={5} defaultValue={JSON.stringify(initial.incompatible_pairs??[],null,2)}/></label>
    <label><input type="checkbox" name="quizEnabled" defaultChecked={Boolean(initial.quiz_enabled)}/> Name Your Rehmat enabled</label><label>Allowed portrait words<textarea name="portraitWords" rows={6} defaultValue={lines(initial.portrait_words)}/></label><label className="full">12-question configuration JSON<textarea name="quizQuestions" rows={12} defaultValue={JSON.stringify(initial.quiz_questions??[],null,2)}/></label>
    <label><input type="checkbox" name="whatsappEnabled" defaultChecked={Boolean(initial.whatsapp_enabled)}/> WhatsApp requests enabled</label><label>WhatsApp number<input name="whatsappNumber" inputMode="numeric" defaultValue={String(initial.whatsapp_number??"")}/></label><label className="full">Default request message<textarea name="whatsappDefaultMessage" rows={3} defaultValue={String(initial.whatsapp_default_message??"")}/></label><label className="full">Confirmation notice<textarea name="whatsappNotice" rows={3} defaultValue={String(initial.whatsapp_notice??"")}/></label>
    <button className="button button-dark" type="submit">Save settings</button><p className="form-message" role="status">{message}</p>
  </form>;
}
