"use client";
import Script from "next/script";
import {useState} from "react";
import {DeliveryAddressFields} from "../../../components/delivery-address-fields";
import {emptyDeliveryAddress,type DeliveryAddress} from "../../../../lib/address";

type Item={productName:string;variantId:string;sizeMl:number;unitPricePaise:number;quantity:number;availableQuantity:number};
type Payment={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
type Options={key:string;amount:number;currency:string;name:string;description:string;order_id:string;prefill:{email:string;contact:string};readonly:{email:boolean;contact:boolean};method:{upi:boolean;card:boolean;netbanking:boolean;wallet:boolean;emi:boolean;paylater:boolean};theme:{color:string};handler:(payment:Payment)=>void;modal:{ondismiss:()=>void}};
const money=(value:number)=>`₹${(value/100).toLocaleString("en-IN")}`;
export function ControlledPaymentTest({items,policyVersion}:{items:Item[];policyVersion:string}){
  const [address,setAddress]=useState<DeliveryAddress>(emptyDeliveryAddress),[approval,setApproval]=useState(""),[refundApproval,setRefundApproval]=useState(""),[paidOrderId,setPaidOrderId]=useState<string|null>(null),[message,setMessage]=useState("Enter the owner-controlled delivery address. Stop before payment authentication."),[busy,setBusy]=useState(false);
  const total=items.reduce((sum,item)=>sum+item.unitPricePaise*item.quantity,0),phrase=`I APPROVE ${money(total)} LIVE PAYMENT`;
  async function begin(){const RazorpayConstructor=window.Razorpay as unknown as (new(options:Options)=>{open:()=>void;on:(event:"payment.failed",callback:(response:{error?:{description?:string}})=>void)=>void})|undefined;if(approval!==phrase||!RazorpayConstructor)return;setBusy(true);setMessage("Preparing the server-authoritative live order…");try{const response=await fetch("/api/create-order",{method:"POST",headers:{"content-type":"application/json","x-rehmat-controlled-test":"live-payment-readiness"},body:JSON.stringify({lines:items.map(item=>({variantId:item.variantId,quantity:item.quantity})),deliveryAddress:{delivery:address,billingSameAsDelivery:true},deliveryPin:address.pinCode,customerIdentifier:address.email,policyAcceptance:{version:policyVersion,acceptedAt:new Date().toISOString(),marketingConsent:false}})});const order=await response.json();if(!response.ok)throw new Error(order.message??"The live test order could not be prepared.");const checkout=new RazorpayConstructor({key:order.public_key_id,amount:order.amount,currency:order.currency,name:"Rehmat Panjab",description:"Owner-approved controlled live readiness payment",order_id:order.order_id,prefill:{email:address.email,contact:address.mobile},readonly:{email:true,contact:true},method:{upi:true,card:true,netbanking:true,wallet:true,emi:false,paylater:false},theme:{color:"#173d32"},handler:async(payment)=>{setMessage("Verifying captured payment…");const verified=await fetch("/api/verify-payment",{method:"POST",headers:{"content-type":"application/json","x-rehmat-controlled-test":"live-payment-readiness"},body:JSON.stringify({...payment,order_token:order.order_token})});const value=await verified.json();if(verified.ok&&value.success)setPaidOrderId(order.internal_order_id);setMessage(verified.ok&&value.success?"Payment captured and verified. Stop here for order, inventory and email checks.":value.message??"Payment verification failed.");setBusy(false);},modal:{ondismiss:()=>{setMessage("Payment window closed without completing the controlled payment.");setBusy(false);}}});checkout.on("payment.failed",()=>{setMessage("The controlled payment failed. Do not retry until Razorpay is checked.");setBusy(false);});checkout.open();}catch(error){setMessage(error instanceof Error?error.message:"The test could not start.");setBusy(false);}}
  async function refund(){if(!paidOrderId||refundApproval!==`I APPROVE ${money(total)} REFUND`)return;setBusy(true);setMessage("Submitting the owner-approved full refund…");try{const response=await fetch("/api/admin/razorpay/refund",{method:"POST",headers:{"content-type":"application/json","x-rehmat-controlled-test":"live-payment-readiness"},body:JSON.stringify({orderId:paidOrderId,amountPaise:total,idempotencyKey:`controlled-live-full-${paidOrderId}`})});const value=await response.json();setMessage(response.ok?"Refund initiated. Verify processed status and the signed webhook before closing this test.":value.message??"Refund could not be initiated.");}catch{setMessage("Refund request could not be completed.");}finally{setBusy(false);}}
  return <section><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><h2>Approved basket</h2><div className="admin-table">{items.map(item=><div key={item.variantId}><strong>{item.productName} · {item.sizeMl} ml × {item.quantity}</strong><span>{money(item.unitPricePaise*item.quantity)}</span><span>{item.availableQuantity} available</span></div>)}<div><strong>Final payable</strong><span>{money(total)}</span><span>No coupon · free shipping threshold met</span></div></div><DeliveryAddressFields value={address} onChange={setAddress}/><label className="full">Type the exact approval phrase only after approving this amount:<input value={approval} onChange={event=>setApproval(event.target.value)} placeholder={phrase}/></label><button className="button button-dark" type="button" disabled={busy||approval!==phrase||items.some(item=>item.availableQuantity<item.quantity)} onClick={begin}>{busy?"Controlled payment in progress…":`Prepare and open ${money(total)} live payment`}</button>{paidOrderId&&<div><label className="full">After separate owner approval, type the exact refund phrase:<input value={refundApproval} onChange={event=>setRefundApproval(event.target.value)} placeholder={`I APPROVE ${money(total)} REFUND`}/></label><button className="button button-outline" type="button" disabled={busy||refundApproval!==`I APPROVE ${money(total)} REFUND`} onClick={refund}>Initiate full {money(total)} refund</button></div>}<p role="status">{message}</p></section>;
}
