"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { useCart } from "../components/cart-provider";
import { formatMoney } from "../../lib/cart";
import { calculateTesterPackPrice, isTesterPackSize, TESTER_PACK_RULES, TESTER_PACK_SIZES, type TesterPackSize } from "../../lib/tester-packs";

type Product={slug:string;name:string;sku:string;pricePaise:number;productId:string;image:string;imageAlt:string;notes:{top:string[];heart:string[];base:string[]}|null};
type LiveTester={variantId:string;productId:string;productSlug:string;productName:string;sku:string;pricePaise:number;availableQuantity:number};

export function TesterBuilder({products,initialPackSize}:{products:Product[];initialPackSize:number}){
  const [packSize,setPackSize]=useState<TesterPackSize>(isTesterPackSize(initialPackSize)?initialPackSize:2),[selected,setSelected]=useState<string[]>([]),[live,setLive]=useState<LiveTester[]>([]),[message,setMessage]=useState("Tester packaging and margins are awaiting approval."),[loading,setLoading]=useState(false);
  const cart=useCart();
  useEffect(()=>{let cancelled=false;fetch("/api/tester-packs/catalogue",{cache:"no-store"}).then(response=>response.json()).then(result=>{if(!cancelled&&Array.isArray(result.items)){setLive(result.items);if(result.items.length)setMessage("Live tester prices and inventory loaded securely.");}}).catch(()=>{});return()=>{cancelled=true;};},[]);
  const liveBySlug=useMemo(()=>new Map(live.map(item=>[item.productSlug,item])),[live]);
  const chosen=products.filter(product=>selected.includes(product.slug));
  const preview=chosen.length===packSize?calculateTesterPackPrice(chosen.map(product=>liveBySlug.get(product.slug)?.pricePaise??product.pricePaise),packSize):null;
  const allLive=chosen.length===packSize&&chosen.every(product=>liveBySlug.has(product.slug));
  function changeSize(size:TesterPackSize){setPackSize(size);setSelected(current=>current.slice(0,size));setMessage(live.length?`Choose ${size} different fragrances.`:"Tester packaging and margins are awaiting approval.");}
  function toggle(slug:string){setSelected(current=>current.includes(slug)?current.filter(item=>item!==slug):current.length<packSize?[...current,slug]:current);}
  async function add(){if(!allLive)return;setLoading(true);setMessage("Rechecking current price and inventory…");try{const selectedLive=chosen.map(product=>liveBySlug.get(product.slug)!);const response=await fetch("/api/tester-packs/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({packSize,variantIds:selectedLive.map(item=>item.variantId)})});const quote=await response.json();if(!response.ok||typeof quote.totalPaise!=="number")throw new Error(quote.message??"The tester pack could not be quoted.");const signature=selectedLive.map(item=>item.variantId).sort().join(":");cart.add({kind:"tester-pack",variantId:`tester-pack:${packSize}:${signature}`,productSlug:"testers",productName:`Pick Any ${packSize} — 3 ml Tester Pack`,sizeMl:3,sku:`RP-TP-${packSize}`,unitPricePaise:quote.totalPaise,currency:"INR",image:"/images/testers/3ml-bottle-draft-reference.jpeg",maxQuantity:Math.min(...selectedLive.map(item=>item.availableQuantity)),testerPack:{packSize,discountPercent:TESTER_PACK_RULES[packSize].discountPercent,selected:selectedLive.map(item=>({variantId:item.variantId,productId:item.productId,productSlug:item.productSlug,productName:item.productName,sku:item.sku}))}});setMessage("Tester pack added. Final price and stock will be rechecked before payment.");}catch(error){setMessage(error instanceof Error?error.message:"The tester pack could not be added.");}finally{setLoading(false);}}
  return <section id="individual-testers" className="tester-builder" aria-labelledby="tester-builder-heading"><div className="tester-builder-heading"><div><p className="eyebrow">Build your pack</p><h2 id="tester-builder-heading">Choose different fragrances.</h2></div><div className="tester-size-tabs" aria-label="Tester pack size">{TESTER_PACK_SIZES.map(size=><button type="button" key={size} className={packSize===size?"is-active":""} aria-pressed={packSize===size} onClick={()=>changeSize(size)}>Pick {size}<small>{TESTER_PACK_RULES[size].discountPercent}% off</small></button>)}</div></div>
    <p className="tester-progress" aria-live="polite">Selected {selected.length} of {packSize}. Duplicate fragrances are not permitted.</p>
    <div className="tester-products">{products.map(product=>{const isSelected=selected.includes(product.slug),atLimit=selected.length>=packSize&&!isSelected,liveItem=liveBySlug.get(product.slug);const notes=product.notes?[product.notes.top[0],product.notes.heart[0],product.notes.base[0]].filter(Boolean):[];return <button type="button" className={isSelected?"tester-product is-selected":"tester-product"} key={product.slug} aria-pressed={isSelected} disabled={atLimit} onClick={()=>toggle(product.slug)}><span className="tester-product-media"><Image src={product.image} alt={product.imageAlt} fill sizes="(max-width: 700px) 44vw, 18vw" unoptimized/></span><span className="tester-product-copy"><strong>{product.name}</strong><small>{notes.length?notes.join(" · "):"Approved fragrance profile"}</small><b>{formatMoney(liveItem?.pricePaise??product.pricePaise)} · 3 ml</b><i>{liveItem?`${liveItem.availableQuantity} available`:"Temporarily unavailable"}</i></span></button>;})}</div>
    <aside className="tester-builder-summary"><div><p className="eyebrow light">Your tester pack</p><h3>{chosen.length===packSize?chosen.map(item=>item.name).join(" · "):`Choose ${packSize-selected.length} more`}</h3><p>{packSize} × 3 ml · one protected corrugated box · no glass-to-glass contact</p></div><div><span>{preview?formatMoney(preview.totalPaise):"—"}</span>{preview&&<small>{preview.discountPercent}% pack saving from {formatMoney(preview.subtotalPaise)}</small>}<button className="button button-cream" type="button" disabled={!allLive||loading} onClick={add}>{loading?"Checking…":allLive?"Add tester pack":"Awaiting packaging approval"}</button></div><p className="tester-builder-message" role="status">{message}</p></aside>
  </section>;
}
