"use client";

import {useRouter} from "next/navigation";
import {useState} from "react";
import {addressPreview,deliveryAddressSchema,emptyDeliveryAddress,type DeliveryAddress} from "../../lib/address";
import {DeliveryAddressFields} from "../components/delivery-address-fields";

type SavedAddress=DeliveryAddress&{id:string;isDefault:boolean};
export function SavedAddresses({initial}:{initial:SavedAddress[]}){const router=useRouter();const [address,setAddress]=useState<DeliveryAddress>(emptyDeliveryAddress),[reviewed,setReviewed]=useState<DeliveryAddress|null>(null),[makeDefault,setMakeDefault]=useState(initial.length===0),[message,setMessage]=useState("");
  function review(){const parsed=deliveryAddressSchema.safeParse(address);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Check the address.");return;}setAddress(parsed.data);setReviewed(parsed.data);setMessage("Review the address before saving.");}
  async function save(){if(!reviewed)return;const response=await fetch("/api/addresses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address:reviewed,isDefault:makeDefault})});const data=await response.json();setMessage(data.message??(response.ok?"Address saved.":"Address could not be saved."));if(response.ok){setAddress(emptyDeliveryAddress);setReviewed(null);router.refresh();}}
  async function act(method:"PATCH"|"DELETE",id:string){const response=await fetch("/api/addresses",{method,headers:{"content-type":"application/json"},body:JSON.stringify(method==="PATCH"?{id,isDefault:true}:{id})});const data=await response.json();setMessage(data.message);if(response.ok)router.refresh();}
  return <section className="saved-addresses"><p className="eyebrow">Delivery details</p><h2>Saved addresses</h2><p>Addresses stay in your private account and are never stored in this browser.</p><div className="saved-address-list">{initial.map(item=><article key={item.id}><strong>{item.recipientName} · {item.addressType}{item.isDefault?" · Default":""}</strong><pre>{addressPreview(item)}</pre><div>{!item.isDefault&&<button type="button" className="text-link" onClick={()=>void act("PATCH",item.id)}>Make default</button>}<button type="button" className="text-link danger" onClick={()=>void act("DELETE",item.id)}>Remove</button></div></article>)}</div><DeliveryAddressFields value={address} onChange={value=>{setAddress(value);setReviewed(null);}} legend="Add a saved address"/><label className="billing-toggle"><input type="checkbox" checked={makeDefault} onChange={e=>setMakeDefault(e.target.checked)}/> Make this my default address</label><button type="button" className="button button-outline" onClick={review}>Review address</button>{reviewed&&<div className="address-preview"><h3>Address preview</h3><pre>{addressPreview(reviewed)}</pre><button type="button" className="text-link" onClick={()=>setReviewed(null)}>Correct address</button><button type="button" className="button button-dark" onClick={()=>void save()}>Save address</button></div>}<p role="status">{message}</p></section>;
}
