import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {merchant,policyConfig} from "../../../lib/merchant";

const policies={
  shipping:{title:"Shipping and Delivery Policy",intro:"Delivery arrangements are confirmed personally before an order is accepted.",items:[["Locations served",policyConfig.shipping.locations],["Processing time",policyConfig.shipping.processing],["Estimated delivery time",policyConfig.shipping.delivery],["Shipping charges",policyConfig.shipping.charges],["Courier method",policyConfig.shipping.courier],["Tracking",policyConfig.shipping.tracking],["Delay handling",policyConfig.shipping.delays],["Incorrect address",policyConfig.shipping.address]]},
  returns:{title:"Cancellation, Return and Refund Policy",intro:"Please contact Rehmat Panjab promptly about cancellation, damage, an incorrect item or a return request.",items:[["Cancellation window",policyConfig.returns.cancellation],["Return window",policyConfig.returns.window],["Opened fragrance oils",policyConfig.returns.opened],["Damaged or incorrect items",policyConfig.returns.damage],["Photographic evidence",policyConfig.returns.evidence],["Return shipping",policyConfig.returns.shipping],["Refund method",policyConfig.returns.method],["Refund timeline",policyConfig.returns.timeline],["Non-returnable situations",policyConfig.returns.excluded]]},
  privacy:{title:"Privacy Policy",intro:"Rehmat Panjab uses personal information only to operate the website, respond to enquiries, fulfil confirmed orders and meet legal obligations.",items:[["Information collected","Contact details, delivery information, account data, consent records, order details and submitted reviews."],["How it is used","To respond on WhatsApp, manage accounts and orders, moderate reviews, send consented updates and improve the website."],["Service providers","Supabase supports account and database functions. Razorpay may process payment information only after online payments are authorized. WhatsApp handles messages sent through its service."],["Cookies and analytics","Essential session technologies may be used. Optional analytics should only operate when configured and lawfully permitted."],["Retention","Records are retained only as needed for service, security, accounting and legal obligations."],["Requests and deletion",merchant.email?`Contact ${merchant.email} to request access, correction or deletion, subject to legal retention duties.`:"The owner must publish a verified privacy email before payment review."]]},
  terms:{title:"Terms and Conditions",intro:"These terms describe use of the Rehmat Panjab website and manually confirmed ordering.",items:[["Merchant identity",merchant.address?`${merchant.name}, ${merchant.address}`:merchant.name],["Website use","Use the website lawfully and provide accurate contact and delivery information."],["Products and prices","Descriptions are considered guidance. Prices and availability are confirmed before an order is accepted."],["WhatsApp ordering","A WhatsApp message is an order request. The order is accepted only after Rehmat Panjab confirms availability, delivery charges and payment details."],["Payment confirmation","Only payment confirmed through an authorized Rehmat Panjab payment channel is accepted as proof of payment."],["Shipping and returns","The published Shipping and Delivery and Cancellation, Return and Refund policies apply."],["Intellectual property","Website text, imagery, branding and design may not be copied without permission."],["Contact",`Contact +91 70094 64475${merchant.email?` or ${merchant.email}`:""}.`]]},
} as const;
export function generateStaticParams(){return Object.keys(policies).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const policy=policies[slug as keyof typeof policies];return policy?{title:policy.title,alternates:{canonical:`/policies/${slug}`}}:{}}
export default async function PolicyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const policy=policies[slug as keyof typeof policies];if(!policy)notFound();return <main id="main-content" className="legal-page"><p className="eyebrow">Rehmat Panjab</p><h1>{policy.title}</h1><p>{policy.intro}</p><dl>{policy.items.filter(([,value])=>Boolean(value)).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Questions about this policy may be directed to <a href="tel:+917009464475">+91 70094 64475</a>.</p></main>}
